services:
  svelte:
    image: todo-svelte:latest
    volumes:
      - ./data:/app/data
    env_file:
      - .env.db_prod
    networks:
      - app-network

  reverse-proxy:
    image: todo-proxy:latest
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env.db_prod
    depends_on:
      - svelte
    networks:
      - app-network

networks:
  app-network:
    driver: bridge